#!/usr/bin/env bash

# This script configures Nginx on an Ubuntu machine to include a custom X-Served-By header in HTTP responses.

# Install Nginx if not already installed
if [ ! -x "$(command -v nginx)" ]; then
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi

# Get the server hostname
server_hostname=$(hostname)

# Configure Nginx to add custom header
sudo sed -i "/server_name _;/a \\n\t# Add custom header\n\tadd_header X-Served-By \"$server_hostname\";" /etc/nginx/sites-available/default

# Restart Nginx for changes to take effect
sudo service nginx restart

# Output for automated scoring
echo "1"
