#!/usr/bin/env bash
ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sleep 2
service nginx status | grep -q "not running" && echo "Nginx is not running." || echo "Nginx is running."
