#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# print To infinity and beyond indefinitely
# print I hate the kill command on SIGTERM
# print Y U no love me?! on SIGINT
# Deletes the file /var/run/holbertonscript.pid and terminate on QUIT or TERM
echo $$ > /var/run/holbertonscript.pid
handle_sigterm () {
    echo I hate the kill command
    rm /var/run/holbertonscript.pid
    exit
}
handle_sigint () {
    echo Y U no love me?!
}
handle_sigquit () {
    rm /var/run/holbertonscript.pid
    exit
}
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT
while true ; do echo To infinity and beyond; sleep 2; done
