#!/bin/bash
# This script is displaying "Best School" 10 times.
# print Hi instead on the 9th iteration
counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
