#!/usr/bin/env bash
# This script runs the whoami command under the user passed as an argument

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

whoami_command=$(which whoami)
if [ -z "$whoami_command" ]; then
    echo "Error: whoami command not found"
    exit 1
fi

sudo -u "$1" $whoami_command
